# Generated by Django 5.0.3 on 2024-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
